

###############################################################################################################################################
###############################################################################################################################################

#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: quodeck
  password: ptotem123
  host: localhost

development:
  <<: *default
  database: cloudops_api_development
  template: template1
test:
  <<: *default
  database: cloudops_api_test
production:
  <<: *default
  database: cloudops_api_production
 
